name: Deploy Ant Pro UI to GitHub Pages
run-name: ${{ github.actor }} triggered by ${{ github.event_name }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # required for GitHub Pages deployment

env:
  BUILD_FOLDER_NAME: dist

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy to GitHub Pages'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          CI: false

      # if you're using Ant Design Pro with Umi, it outputs to /dist by default
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.BUILD_FOLDER_NAME }}
          publish_branch: gh-pages
