# Need to manual remove all contents in /var/www/html
name: Deploy Prod Tencent bitcode-lab.com
run-name: ${{ github.actor }} trigger by ${{github.event_name}}
on: [workflow_dispatch]
jobs:
  checkout-branch:
    name: 'Checkout Branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build:
    name: 'Node Build'
    needs: [checkout-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false

  upload-build:
    name: 'Upload Build'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.TENCENT_CLOUD_SSH_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_KEY }}
          port: ${{ secrets.PORT }}
          source: 'dist/*'
          target: '~/temp/mdc'

  move-build:
    name: 'Move Build'
    needs: [upload-build]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.TENCENT_CLOUD_SSH_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /var/www/html/mdc
            mv ~/temp/mdc/build/* /var/www/html/mdc
